name: "Terraform Deploy"

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}

    # ---------------------------------------------
    # Terraform Quality Check - fmt & lint
    # ---------------------------------------------
    - name: Terraform Quality Check
      uses: ./.github/actions/terraform/quality

    # ---------------------------------------------
    # Terraform Init - Get env backend
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        ls -la
        echo "Initializing Terraform with backend: ${{ inputs.backend-file-path }}"
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

    # ---------------------------------------------
    # Terraform Validate
    # --------------------------------------------- 
    - name: Terraform Validate
      shell: bash
      run: terraform validate

    # ---------------------------------------------
    # Terraform Plan       
    # ---------------------------------------------
    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        terraform plan \
          -input=false \
          -no-color \
          -var-file="${{ inputs.tfvars-file }}" 
          -out=tfplan
    # terraform plan \
    #   -var-file="${{ inputs.tfvars-file }}" \
    #   -out=tfplan \
    #   -detailed-exitcode
    # echo "exitcode=$?" >> $GITHUB_OUTPUT
#sji todoremove
# terraform import 'module.eks.module.eks.module.kms.aws_kms_alias.this["cluster"]' alias/eks/catalina-dev
    # ---------------------------------------------
    # Terraform Show Plan
    # ---------------------------------------------
    - name: Show Plan
      if: steps.plan.outputs.exitcode != '0'
      shell: bash
      run: terraform show -no-color tfplan

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ inputs.environment }}
        path: tfplan
        retention-days: 30

    - name: Terraform Apply
      shell: bash
      if: ${{ inputs.auto-apply }}
      run: |
        terraform apply -auto-approve tfplan