name: "Terraform Deploy"
inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file:
    required: true
  auto-apply:
    type: boolean
    default: true
  working-directory:
    required: false

runs:
  using: "composite"
  steps:
    - name: Enter working_directory directory
      run: |
        set -e
        [ -d "${{ inputs.working-directory }}" ] || (echo "${{ inputs.working-directory }}/ not found!" && ls -la && exit 1)
        cd ${{ inputs.working-directory }}
        echo "Working in: $(pwd)"
      shell: bash

    # ---------------------------------------------
    # 1. Get Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # 2. Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    # ---------------------------------------------
    # 3. Terraform Quality Check
    # ---------------------------------------------
    - name: Terraform Quality Check
      uses: ./.github/actions/terraform/quality
      with:
        terraform_version: ${{ steps.tf-version.outputs.version }}

    # ---------------------------------------------
    # 4. Terraform Init
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        terraform init \
          -backend-config="${{ inputs.backend-file }}"

    # ---------------------------------------------
    # 5. Terraform Validate
    # --------------------------------------------- 
    - name: Terraform Validate
      shell: bash
      run: terraform validate

    # ---------------------------------------------
    # 6. Terraform Plan       
    # ---------------------------------------------
    - name: Terraform Plan
      id: plan
      shell: bash
      env:
        TF_VAR_environment: ${{ inputs.environment }}
      run: |
        terraform plan \
          -var-file="${{ inputs.tfvars-file }}" \
          -out=tfplan \
          -detailed-exitcode
        echo "plan_exitcode=$?" >> $GITHUB_OUTPUT

    # ---------------------------------------------
    # 7. Terraform Show Plan
    # ---------------------------------------------
    - name: Show Plan
      if: steps.plan.outputs.exitcode != '0'
      run: terraform show -no-color tfplan

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ inputs.environment }}
        path: tfplan

    - name: Terraform Apply
      shell: bash
      if: ${{ inputs.auto-apply && steps.plan.outputs.exitcode == '2' }}
      run: terraform apply -auto-approve tfplan