name: "Terraform Deploy"

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # 1. Get Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # 2. Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}

    # ---------------------------------------------
    # 3. Terraform Quality Check - fmt & lint
    # ---------------------------------------------
    #- name: Terraform Quality Check
    #  uses: ./.github/actions/terraform/quality

    # ---------------------------------------------
    # 4. Terraform Init - Get env backend
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        ls -la
        echo "Initializing Terraform with backend: ${{ inputs.backend-file-path }}"
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

    # TEMP! releases lock file for tfstate fuck ups
    #find in console/dynamodb/lock table/Explore table items (top right)
    - name: Release stale lock (works every time)
      shell: bash
      run: |
        echo "Forcing unlock of any stale lock â€“ safe if none exists"
        terraform force-unlock -force a47c9845-cf4b-d2be-e081-4d598c43a0b8 || true
      continue-on-error: true

    # ---------------------------------------------
    # 5. Terraform Validate
    # --------------------------------------------- 
    - name: Terraform Validate
      shell: bash
      run: terraform validate

    # ---------------------------------------------
    # 6. Terraform Plan       
    # ---------------------------------------------
    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        terraform plan \
          -var-file="${{ inputs.tfvars-file }}" \
          -out=tfplan \
          -detailed-exitcode
        echo "exitcode=$?" >> $GITHUB_OUTPUT
#sji todo - lock false remove for release
# terraform import 'module.eks.module.eks.module.kms.aws_kms_alias.this["cluster"]' alias/eks/catalina-dev
    # ---------------------------------------------
    # 7. Terraform Show Plan
    # ---------------------------------------------
    - name: Show Plan
      if: steps.plan.outputs.exitcode != '0'
      shell: bash
      run: terraform show -no-color tfplan

    # - name: Upload Plan
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: tfplan-${{ inputs.environment }}
    #     path: tfplan
    #     retention-days: 30

    # - name: Terraform Apply
    #   shell: bash
    #   if: ${{ inputs.auto-apply }}
    #   run: |
    #     terraform apply -auto-approve tfplan